name: isit_busy
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  easy_splash_screen: ^1.0.3
  firebase_core: ^1.12.0
  cloud_firestore: ^3.1.7
  firebase_auth: ^3.3.6
  image_picker: ^0.8.5+3
  url_launcher: ^6.0.20
  flutter_facebook_auth: ^4.1.1
  shared_preferences: ^2.0.13
  firebase_storage: ^10.2.9
  modal_progress_hud_nsn: ^0.1.0-nullsafety-0
  flutter_rating_bar: ^4.0.0
  timeago: ^3.2.2
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true


  flutter_lints: ^1.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/images/



